package com.lsn.hibernation.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lsn.hibernation.db.bean.MusicWithSinger;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MUSIC_WITH_SINGER".
*/
public class MusicWithSingerDao extends AbstractDao<MusicWithSinger, Long> {

    public static final String TABLENAME = "MUSIC_WITH_SINGER";

    /**
     * Properties of entity MusicWithSinger.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StrId = new Property(1, String.class, "StrId", false, "STR_ID");
        public final static Property SId = new Property(2, String.class, "sId", false, "S_ID");
        public final static Property MId = new Property(3, String.class, "mId", false, "M_ID");
    }


    public MusicWithSingerDao(DaoConfig config) {
        super(config);
    }
    
    public MusicWithSingerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MUSIC_WITH_SINGER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"STR_ID\" TEXT," + // 1: StrId
                "\"S_ID\" TEXT," + // 2: sId
                "\"M_ID\" TEXT);"); // 3: mId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MUSIC_WITH_SINGER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MusicWithSinger entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String StrId = entity.getStrId();
        if (StrId != null) {
            stmt.bindString(2, StrId);
        }
 
        String sId = entity.getSId();
        if (sId != null) {
            stmt.bindString(3, sId);
        }
 
        String mId = entity.getMId();
        if (mId != null) {
            stmt.bindString(4, mId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MusicWithSinger entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String StrId = entity.getStrId();
        if (StrId != null) {
            stmt.bindString(2, StrId);
        }
 
        String sId = entity.getSId();
        if (sId != null) {
            stmt.bindString(3, sId);
        }
 
        String mId = entity.getMId();
        if (mId != null) {
            stmt.bindString(4, mId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MusicWithSinger readEntity(Cursor cursor, int offset) {
        MusicWithSinger entity = new MusicWithSinger( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // StrId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // mId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MusicWithSinger entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStrId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MusicWithSinger entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MusicWithSinger entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MusicWithSinger entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
