package com.lsn.hibernation.db.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.lsn.hibernation.db.bean.MusicWithSinger;

import com.lsn.hibernation.db.bean.Singer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SINGER".
*/
public class SingerDao extends AbstractDao<Singer, String> {

    public static final String TABLENAME = "SINGER";

    /**
     * Properties of entity Singer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property NetId = new Property(1, String.class, "netId", false, "NET_ID");
        public final static Property QQId = new Property(2, String.class, "QQId", false, "QQID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
    }

    private DaoSession daoSession;

    private Query<Singer> music_SingersQuery;

    public SingerDao(DaoConfig config) {
        super(config);
    }
    
    public SingerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SINGER\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NET_ID\" TEXT," + // 1: netId
                "\"QQID\" TEXT," + // 2: QQId
                "\"NAME\" TEXT);"); // 3: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SINGER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Singer entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String netId = entity.getNetId();
        if (netId != null) {
            stmt.bindString(2, netId);
        }
 
        String QQId = entity.getQQId();
        if (QQId != null) {
            stmt.bindString(3, QQId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Singer entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String netId = entity.getNetId();
        if (netId != null) {
            stmt.bindString(2, netId);
        }
 
        String QQId = entity.getQQId();
        if (QQId != null) {
            stmt.bindString(3, QQId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
    }

    @Override
    protected final void attachEntity(Singer entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Singer readEntity(Cursor cursor, int offset) {
        Singer entity = new Singer( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // netId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // QQId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Singer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNetId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setQQId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Singer entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Singer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Singer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "singers" to-many relationship of Music. */
    public List<Singer> _queryMusic_Singers(String mId) {
        synchronized (this) {
            if (music_SingersQuery == null) {
                QueryBuilder<Singer> queryBuilder = queryBuilder();
                queryBuilder.join(MusicWithSinger.class, MusicWithSingerDao.Properties.SId)
                    .where(MusicWithSingerDao.Properties.MId.eq(mId));
                music_SingersQuery = queryBuilder.build();
            }
        }
        Query<Singer> query = music_SingersQuery.forCurrentThread();
        query.setParameter(0, mId);
        return query.list();
    }

}
